name: frontend_deploy
on:
  push:
    branches: main
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 2
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::328406402605:role/github-deployer
        aws-region: us-east-1
    - name: Deployment Steps
      run: |
        IS_FRONTEND=`git diff-tree --name-only -r HEAD^ HEAD|tr " " "\n" |grep -Ec "^frontend/src\/|^frontend/public\/" || true`
        if [ $IS_FRONTEND -eq 0 ];then
          echo "No frontend files found exiting !"
          exit 0
        fi
        echo "✅ Frontend Files found, starting deployment ...."
        cd frontend
        npm install
        npm run build || true
        aws --version
        env|grep AWS
        aws s3 ls
        aws s3 sync ./build s3://$FRONTEND_BUCKET_NAME
        aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
      env:	
        CDN_DISTRIBUTION_ID: ${{ secrets.CARE_CLINIC_CDN_DISTRIBUTION_ID }}
        FRONTEND_BUCKET_NAME: ${{ secrets.CARE_CLINIC_FRONTEND_BUCKET_NAME }}
        